<?php
/**
 * @file
 * Trailmapin ytimen toiminnallisuus
 */


function trailmap_help($path,$arg) {
    switch ($path) {
        case 'admin/help#trailmap':
            return '<p>' . t('Trailmap toiminnallisuus') . '</p>';
            break;
    }
}

/*
function trailmap_node_info() {
    return Array(
            'upload' => Array(
                'name' => t('Jäljen lataus'),
                'base' => 'trailmap',
                'description' => t('GPX jäljen lataus Trailmapiin')
                ),
            'view' => Array(
                'name' => t('Polkujen katselu'),
                'base' => 'trailmap',
                'description' => t('Polkujen katselu')
                )
        );
}
*/

function trailmap_menu() {
    $items['trailmap'] = Array(
            'page callback' => 'trailmap_front_view',
            'access arguments' => array('access content'),
            'file'=> 'trailmap.front.inc.php',
            'title'=>t('Trailmap'),
            );

    $items['trailmap/upload'] = Array(
            'page callback' => 'trailmap_upload_view',
            'access arguments' => array('access content'),
            'file'=> 'trailmap.upload.inc.php',
            'title'=>t('Jälkien lataus')
            );

    $items['trailmap/me'] = Array(
            'page callback' => 'trailmap_me_view',
            'access arguments' => array('access content'),
            'file'=> 'trailmap.me.inc.php',
            'title'=>t('Omat tiedot')
            );

    $items['trailmap/tracks/%/delete'] = Array(
            'page callback' => 'trailmap_track_delete',
            'access arguments' => array('access content'),
            'file'=> 'trailmap.track_delete.inc.php',
            'type' => MENU_CALLBACK,
            'title' => 'Delete track',
            'page arguments' => array(2)
            );


    return $items;
}


function tailmap_preprocess_block(&$variables) {
  $variables['template_files'][] = 'trailmap_front';
}


function trailmap_theme(){
    return array(
        'front' => array(
            'template' => 'front'//name of template file, place test.tpl.php in your module
        )
    );
}

function trailmap_permission() {
    return Array(
        'upload gpx' => Array(
                'title' => t('Lähettää GPX trackejä'),
                'description' => t('Lähettää GPX trackejä Trailmapiin')
            ),
        );
}